<a href="https://colab.research.google.com/github/Thecaiobr/Topicos-3/blob/main/AS02_Representa%C3%A7%C3%A3o_Textual.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn.datasets import fetch_20newsgroups
newsgroups_train = fetch_20newsgroups(subset='train')

from pprint import pprint
pprint(list(newsgroups_train.target_names))

['alt.atheism',
 'comp.graphics',
 'comp.os.ms-windows.misc',
 'comp.sys.ibm.pc.hardware',
 'comp.sys.mac.hardware',
 'comp.windows.x',
 'misc.forsale',
 'rec.autos',
 'rec.motorcycles',
 'rec.sport.baseball',
 'rec.sport.hockey',
 'sci.crypt',
 'sci.electronics',
 'sci.med',
 'sci.space',
 'soc.religion.christian',
 'talk.politics.guns',
 'talk.politics.mideast',
 'talk.politics.misc',
 'talk.religion.misc']


In [ ]:
C = ['The who is the band!',
     'who is the band?',
     'The band who plays the who']

print("C has %d texts:" % len(C))
for i in range(len(C)):
  print('t{} = {}'.format(i+1, C[i]))

import re

def get_tokens(text):
  tokens = re.sub("[^\w]", " ", text).split()
  cleaned_text = [w.lower() for w in tokens]
  return cleaned_text

def tokenize(texts):
  words = []
  for text in texts:
    w = get_tokens(text)
    words.extend(w)
    words = sorted(list(set(words)))
  return words

V = tokenize(C)
print("V has {0} words: {1}".format(len(V),V))


import numpy

for text in C:
  words = get_tokens(text)
  bag_vector = numpy.zeros(len(V))
  for w in words:
    for i, word in enumerate(V):
      if word == w:
        bag_vector[i] = 1
  print("{0} = {1}".format(text,numpy.array(bag_vector)))

C has 3 texts:
t1 = The who is the band!
t2 = who is the band?
t3 = The band who plays the who
V has 5 words: ['band', 'is', 'plays', 'the', 'who']
The who is the band! = [1. 1. 0. 1. 1.]
who is the band? = [1. 1. 0. 1. 1.]
The band who plays the who = [1. 0. 1. 1. 1.]


In [ ]:
from sklearn.datasets import fetch_20newsgroups

# Carregar o conjunto de dados
newsgroups_data = fetch_20newsgroups(subset='train')


In [ ]:
import re

def get_tokens(text):
    tokens = re.sub("[^\w]", " ", text).split()
    cleaned_text = [w.lower() for w in tokens]
    return cleaned_text

def tokenize(texts):
    words = []
    for text in texts:
        w = get_tokens(text)
        words.extend(w)
    words = sorted(list(set(words)))
    return words

def preProcessCorpus(corpus):
  newCorpus = [doc.lower() for doc in corpus]
  regex = r"(?<!\d)[\!?.,;:-](?!\d)"
  newCorpus = [re.sub(regex, "", doc, 0) for doc in newCorpus]
  return newCorpus

# Extrair os textos do conjunto de dados
# ESSES VALORES PODEM SER ALTERADOS entre 0 e 20 sendo [0:20] para rodar todos textos)
# No codigo abaixo esta contido o codigo para rodar os 3 primeiros conjuntos de texto
C = newsgroups_data.data[:3]

print("C has %d texts:" % len(C))
for i in range(len(C)):
    print('t{} = {}'.format(i+1, C[i]))

# Tokenizar os textos para obter o vocabulário
V = tokenize(C)
print("V has {0} words: {1}".format(len(V), V))

#ONE-HOT ENCODING
import numpy as np

with open("20News_01.txt", "w") as file:
  for text in C:
      words = get_tokens(text)
      bag_vector = np.zeros(len(V))
      for w in words:
          for i, word in enumerate(V):
              if word == w:
                  bag_vector[i] = 1
      print("{0} = {1}".format(text, np.array(bag_vector)))
      file.write("{0} = {1}\n".format(text, np.array(bag_vector)))


C has 3 texts:
t1 = From: lerxst@wam.umd.edu (where's my thing)
Subject: WHAT car is this!?
Nntp-Posting-Host: rac3.wam.umd.edu
Organization: University of Maryland, College Park
Lines: 15

 I was wondering if anyone out there could enlighten me on this car I saw
the other day. It was a 2-door sports car, looked to be from the late 60s/
early 70s. It was called a Bricklin. The doors were really small. In addition,
the front bumper was separate from the rest of the body. This is 
all I know. If anyone can tellme a model name, engine specs, years
of production, where this car is made, history, or whatever info you
have on this funky looking car, please e-mail.

Thanks,
- IL
   ---- brought to you by your neighborhood Lerxst ----





t2 = From: guykuo@carson.u.washington.edu (Guy Kuo)
Subject: SI Clock Poll - Final Call
Summary: Final call for SI clock reports
Keywords: SI,acceleration,clock,upgrade
Article-I.D.: shelley.1qvfo9INNc3s
Organization: University of Washington
Lines: 11
NNTP-

In [ ]:
# import re
# import numpy as np
# from sklearn.datasets import fetch_20newsgroups

# def get_tokens(text):
#     tokens = re.sub("[^\w]", " ", text).split()
#     cleaned_text = [w.lower() for w in tokens]
#     return cleaned_text

# def tokenize(texts):
#     words = []
#     for text in texts:
#         w = get_tokens(text)
#         words.extend(w)
#     words = sorted(list(set(words)))
#     return words

# # Extrair os textos do conjunto de dados
# newsgroups_data = fetch_20newsgroups(subset='train')
# C = newsgroups_data.data[:3]

# print("C has %d texts:" % len(C))
# for i in range(len(C)):
#     print('t{} = {}'.format(i+1, C[i]))

# # Tokenizar os textos para obter o vocabulário
# V = tokenize(C)
# print("V has {0} words: {1}".format(len(V), V))

# # Criar vetores one-hot encoding para cada texto usando o vocabulário comum
# for text in C:
#     words = get_tokens(text)
#     bag_vector = np.zeros(len(V))
#     for w in words:
#         if w in V:
#             idx = V.index(w)
#             bag_vector[idx] = 1
#     print("{0} = {1}".format(text, np.array(bag_vector)))


C has 3 texts:
t1 = From: lerxst@wam.umd.edu (where's my thing)
Subject: WHAT car is this!?
Nntp-Posting-Host: rac3.wam.umd.edu
Organization: University of Maryland, College Park
Lines: 15

 I was wondering if anyone out there could enlighten me on this car I saw
the other day. It was a 2-door sports car, looked to be from the late 60s/
early 70s. It was called a Bricklin. The doors were really small. In addition,
the front bumper was separate from the rest of the body. This is 
all I know. If anyone can tellme a model name, engine specs, years
of production, where this car is made, history, or whatever info you
have on this funky looking car, please e-mail.

Thanks,
- IL
   ---- brought to you by your neighborhood Lerxst ----





t2 = From: guykuo@carson.u.washington.edu (Guy Kuo)
Subject: SI Clock Poll - Final Call
Summary: Final call for SI clock reports
Keywords: SI,acceleration,clock,upgrade
Article-I.D.: shelley.1qvfo9INNc3s
Organization: University of Washington
Lines: 11
NNTP-

In [ ]:
#COUNT VECTORS
with open("20News_02.txt", "w") as file:
  for text in C:
      words = get_tokens(text)
      bag_vector = np.zeros(len(V))
      for w in words:
          for i, word in enumerate(V):
              if word == w:
                  bag_vector[i] += 1
      print("{0} = {1}".format(text, np.array(bag_vector)))
      file.write("{0} = {1}\n".format(text, np.array(bag_vector)))

From: lerxst@wam.umd.edu (where's my thing)
Subject: WHAT car is this!?
Nntp-Posting-Host: rac3.wam.umd.edu
Organization: University of Maryland, College Park
Lines: 15

 I was wondering if anyone out there could enlighten me on this car I saw
the other day. It was a 2-door sports car, looked to be from the late 60s/
early 70s. It was called a Bricklin. The doors were really small. In addition,
the front bumper was separate from the rest of the body. This is 
all I know. If anyone can tellme a model name, engine specs, years
of production, where this car is made, history, or whatever info you
have on this funky looking car, please e-mail.

Thanks,
- IL
   ---- brought to you by your neighborhood Lerxst ----




 = [0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 1. 0. 0. 3. 0. 0. 0. 0. 0. 0.
 0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 2. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.
 0. 1. 0. 0. 1. 0. 1. 1. 0. 0. 1. 0. 1. 1. 5. 0. 0. 0. 1. 0. 0. 0. 1. 0.
 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 1. 1.

In [ ]:
#TF-IDF Vectors
import sklearn
import pandas as pd
import nltk
from sklearn.feature_extraction.text import CountVectorizer

corpus = preProcessCorpus(C)
print(corpus)

vectorizer = CountVectorizer()
docTermMatrix = vectorizer.fit_transform(corpus)
terms = vectorizer.get_feature_names_out()

print(pd.DataFrame(docTermMatrix.A, columns=terms).to_string())

["from lerxst@wamumdedu (where's my thing)\nsubject what car is this\nnntppostinghost rac3.wamumdedu\norganization university of maryland college park\nlines 15\n\n i was wondering if anyone out there could enlighten me on this car i saw\nthe other day it was a 2-door sports car looked to be from the late 60s/\nearly 70s it was called a bricklin the doors were really small in addition\nthe front bumper was separate from the rest of the body this is \nall i know if anyone can tellme a model name engine specs years\nof production where this car is made history or whatever info you\nhave on this funky looking car please email\n\nthanks\n il\n    brought to you by your neighborhood lerxst \n\n\n\n\n", "from guykuo@carsonuwashingtonedu (guy kuo)\nsubject si clock poll  final call\nsummary final call for si clock reports\nkeywords siaccelerationclockupgrade\narticleid shelley.1qvfo9innc3s\norganization university of washington\nlines 11\nnntppostinghost carsonuwashingtonedu\n\na fair number 

In [ ]:
#TF-IDF Vectors
from sklearn.feature_extraction.text import TfidfTransformer

transformer = TfidfTransformer()
tfIdMatrix = transformer.fit_transform(docTermMatrix)

print(pd.DataFrame(tfIdMatrix.A, columns=terms).to_string())

with open("20News_03.txt", "w") as file:
  file.write(pd.DataFrame(tfIdMatrix.A, columns=terms).to_string());

        11       120        15       160       180      185c      1985  1qvfo9innc3s        36      512k       60s       70s      800      80mb     about    access    active  actually  adapters      add  addition   advance     after       all        an       and    answer  answered       any   anybody   anymore    anyone  appearence       are    around  articleid        as        at  attained      back     base        be    better       bit      body    brave   breifly  bricklin    brief   brought    bumper     bunch       but        by     call    called       can       car    cards  carsonuwashingtonedu     clock   college  computer  convictions    corner     could      cpu     daily  dangerous       day     days  daytoday  detailing      dirt      disk   display  distribution      does       don     done      door     doors     drops       duo     early  ececnpurdueedu  ecnpurdueedu  electrical     email   enemies    engine  engineering  enlighten  especially  expected  experiences 

In [ ]:
vectorizer.vocabulary_

{'from': 106,
 'lerxst': 148,
 'wamumdedu': 287,
 'where': 298,
 'my': 174,
 'thing': 266,
 'subject': 251,
 'what': 295,
 'car': 57,
 'is': 139,
 'this': 267,
 'nntppostinghost': 182,
 'rac3': 215,
 'organization': 190,
 'university': 277,
 'of': 184,
 'maryland': 165,
 'college': 61,
 'park': 194,
 'lines': 153,
 '15': 2,
 'was': 288,
 'wondering': 303,
 'if': 131,
 'anyone': 31,
 'out': 193,
 'there': 265,
 'could': 65,
 'enlighten': 92,
 'me': 167,
 'on': 185,
 'saw': 228,
 'the': 263,
 'other': 192,
 'day': 69,
 'it': 140,
 'door': 80,
 'sports': 248,
 'looked': 155,
 'to': 271,
 'be': 41,
 'late': 147,
 '60s': 10,
 'early': 84,
 '70s': 11,
 'called': 55,
 'bricklin': 47,
 'doors': 81,
 'were': 294,
 'really': 221,
 'small': 238,
 'in': 134,
 'addition': 20,
 'front': 107,
 'bumper': 50,
 'separate': 230,
 'rest': 225,
 'body': 44,
 'all': 23,
 'know': 144,
 'can': 56,
 'tellme': 259,
 'model': 170,
 'name': 175,
 'engine': 90,
 'specs': 246,
 'years': 307,
 'production': 210,
 'm

In [ ]:
#CO-OCCURRENCE VECTORS
co_occurrence_matrix = (docTermMatrix.T * docTermMatrix)
print(co_occurrence_matrix.todense())

[[1 0 0 ... 0 1 1]
 [0 1 0 ... 0 1 0]
 [0 0 1 ... 1 2 1]
 ...
 [0 0 1 ... 1 2 1]
 [1 1 2 ... 2 6 3]
 [1 0 1 ... 1 3 2]]


In [ ]:
import scipy.sparse as sp
g = sp.diags(1./co_occurrence_matrix.diagonal())
co_occurrence_matrix_norm = g * co_occurrence_matrix

print(co_occurrence_matrix_norm.todense())

with open("20News_04.txt", "w") as file:
    file.write("Co-Occurrence Matrix:\n")
    file.write("{0}\n\n".format(co_occurrence_matrix.todense()))

    file.write("Normalized Co-Occurrence Matrix:\n")
    file.write("{0}\n".format(co_occurrence_matrix_norm.todense()))

[[1.         0.         0.         ... 0.         1.         1.        ]
 [0.         1.         0.         ... 0.         1.         0.        ]
 [0.         0.         1.         ... 1.         2.         1.        ]
 ...
 [0.         0.         1.         ... 1.         2.         1.        ]
 [0.16666667 0.16666667 0.33333333 ... 0.33333333 1.         0.5       ]
 [0.5        0.         0.5        ... 0.5        1.5        1.        ]]


In [ ]:
#N-GRAMS
vectorizer = CountVectorizer(ngram_range=(2,2))
docTermMatrix = vectorizer.fit_transform(corpus)
vocabulary = vectorizer.get_feature_names_out()
terms = vectorizer.get_feature_names_out()

print(pd.DataFrame(docTermMatrix.A, columns=terms).to_string())

with open("20News_05.txt", "w") as file:
    file.write(pd.DataFrame(docTermMatrix.A, columns=vocabulary).to_string())

   11 nntppostinghost  120 but  15 was  160 and  160 or  180 and  180 could  180 daytoday  180 if  185c was  1985 sooo  1qvfo9innc3s organization  36 well  512k way  60s early  70s it  800 and  80mb disk  about price  access to  active display  actually uses  adapters heat  add on  add to  addition the  advance for  after starting  all know  all wow  an appearence  and 180  and adapters  and figured  and floppies  and have  and haven  and money  and since  answer does  answered this  any dirt  any info  anybody heard  anybody know  anybody out  anymore on  anyone can  anyone out  appearence this  are especially  are expected  are more  around the  around with  articleid shelley  as 512k  at premium  attained cpu  back in  base if  be from  be looking  be summarizing  better the  bit sooner  body this  brave souls  breifly and  bricklin the  brief message  brought to  bumper was  bunch in  bunch of  but don  but haven  but is  but ve  by your  call for  call summary  called bricklin  ca

In [ ]:
#WORD2VEC
import spacy
nlp = spacy.load('en_core_web_sm')
bag_vector = [nlp(sentence).vector for sentence in corpus]

print(bag_vector)

with open("20News_06.txt", "w") as file:
    for i, vector in enumerate(bag_vector):
        file.write("Vector {0}:\n".format(i+1))
        file.write("{0}\n\n".format(vector))

[array([ 9.05849636e-02, -1.49783850e-01, -1.87406898e-01,  3.28881629e-02,
        3.73076014e-02, -1.73430905e-01,  2.00760439e-01,  3.36019665e-01,
        2.31657252e-02,  1.54251963e-01, -2.19211698e-01,  3.28957468e-01,
       -1.70752123e-01,  6.92420900e-02, -8.84963796e-02, -1.18376322e-01,
        8.60196948e-02,  2.62950987e-01, -2.51212299e-01,  2.99625974e-02,
        7.88094848e-03,  4.60637510e-01, -4.29236665e-02, -3.24388117e-01,
       -8.64428654e-02, -2.83487171e-01,  1.84106931e-01,  1.75417185e-01,
        2.27715403e-01, -1.11076020e-01,  9.95579138e-02,  4.91396151e-02,
        3.00786376e-01, -2.04363599e-01,  3.25420439e-01, -4.36686844e-01,
        3.51743668e-01,  1.65837966e-02, -2.27002814e-01,  1.36586046e-03,
       -2.25742877e-01,  2.51815766e-01,  1.83065012e-01, -5.00626815e-03,
        9.21757296e-02, -5.32008931e-02, -5.18620275e-02,  2.38205358e-01,
       -2.10518122e-01, -1.54778719e-01, -5.48150837e-01,  5.44373468e-02,
        4.99219038e-02, 